# Generated by Django 2.2 on 2021-09-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=11, verbose_name='面试官姓名')),
                ('evaluate', models.CharField(max_length=100, verbose_name='评价')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='姓名')),
                ('sex', models.CharField(max_length=5, verbose_name='性别')),
                ('classroom', models.CharField(max_length=11, verbose_name='班级')),
                ('studentID', models.CharField(max_length=20, verbose_name='学号')),
                ('phone', models.CharField(max_length=20, verbose_name='手机')),
                ('QQnumber', models.CharField(max_length=20, verbose_name='QQ号码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('photo', models.ImageField(null=True, upload_to='photo')),
                ('learnt_skill', models.CharField(max_length=500, verbose_name='掌握的技术能力')),
                ('familiar_skill', models.CharField(max_length=200, verbose_name='熟练掌握的技术能力')),
                ('nontech_skill', models.CharField(max_length=300, verbose_name='非技术能力')),
                ('orgnization', models.CharField(max_length=100, verbose_name='有意向/已加入的其他学生组织')),
                ('reason', models.CharField(max_length=200, verbose_name='加入科协的理由')),
                ('valued', models.CharField(max_length=200, verbose_name='在科协你最期望收获到的三样东西')),
                ('is_resume', models.BooleanField(verbose_name='简历是否审核通过')),
                ('is_writetest', models.BooleanField(verbose_name='笔试是否通过')),
                ('write_score', models.IntegerField(verbose_name='笔试分数')),
                ('write_detail', models.CharField(max_length=100, verbose_name='笔试详情')),
                ('is_interview', models.BooleanField(verbose_name='面试是否通过')),
                ('interview_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.InterviewInfo')),
            ],
        ),
    ]
