# Generated by Django 2.2 on 2021-09-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210906_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='city',
            field=models.CharField(default=None, max_length=30, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='is_interview',
            field=models.NullBooleanField(default=None, verbose_name='面试是否通过'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='is_resume',
            field=models.NullBooleanField(default=None, verbose_name='简历是否审核通过'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='is_writetest',
            field=models.NullBooleanField(default=None, verbose_name='笔试是否通过'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='write_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='笔试详情'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='write_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='笔试分数'),
        ),
    ]
